services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Arobases\SyliusInstagramPlugin\Twig\:
    resource: '../../Twig'




  Arobases\SyliusInstagramPlugin\Form\Extension\ChannelTypeExtension:
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\ChannelBundle\Form\Type\ChannelType }